import { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className='no-scrollbar'>
      <body className='bg-[#141414] text-white'>{children}</body>
    </html>
  );
}
