version: '3.9'

services:
  app:
    image: pedropereiraassis/docker-node
    container_name: app
    working_dir: /app
    command: dockerize -wait tcp://db:3306 -timeout 20s npm start
    volumes:
      - .:/app
    tty: true
    networks: 
      - node-network
    depends_on:
      - db
    restart: on-failure
    ports:
      - '3000:3000'
  
  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0
    volumes:
      - ./.db:/var/lib/mysql
    restart: always
    tty: true
    networks: 
      - node-network
    ports:
      - '3307:3306'
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8080:80'
    tty: true
    networks: 
      - node-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

networks:
  node-network:
    driver: bridge
