FROM node:20.9-alpine AS builder

WORKDIR /usr/src/app

COPY . .

RUN npm install

ENV DOCKERIZE_VERSION v0.7.0

RUN apk update --no-cache \
    && apk add --no-cache wget openssl \
    && wget -O - https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz | tar xzf - -C /usr/local/bin

EXPOSE 3000

CMD [ "npm", "start" ]