POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane@email.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
  "clientId": "c00607c9-e8be-4c79-b1e6-a032008bd7eb"
}
###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "accountIdFrom": "b6ec1407-6fdb-4e91-8376-064723cb9d15",
  "accountIdTo": "bc3291c5-15bc-4603-8c59-2bb5d92a4c3f",
  "amount": 50
}